title: "CONQ34 – AIO 2025 Blog"
description: "Nhật ký học Machine Learning của nhóm CONQ34 – AIO 2025"
theme: minima
url: "https://uyentran9.github.io"
baseurl: "/CONQ34-AIO2025"

author: Uyen Tran (Victoria Tran)
markdown: kramdown
plugins:
  - jekyll-feed
