title: "CONQ34 – AIO 2025 Blog"
description: "Nhật ký học AI của nhóm CONQ34 – AIO 2025"
theme: minima
url: "https://uyentran9.github.io"
baseurl: "/CONQ34-AIO2025"

author: Uyen Tran (Victoria Tran)
markdown: kramdown
plugins:
  - jekyll-feed
header_pages:
  - about.md
  - modules.md
  - team.md
