# =========================
# Site settings
# =========================
title: "CONQ34 – AIO 2025 Blog"
description: "Nhật ký học AI của nhóm CONQ34 – AIO 2025"
author: "Uyen Tran (Victoria Tran)"

# =========================
# URL settings
# =========================
url: "https://uyentran9.github.io"
baseurl: "/CONQ34-AIO2025"

# =========================
# Theme and Markdown Engine
# =========================
theme: minima

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  hard_wrap: false
  parse_block_html: false
  syntax_highlighter_opts:
    block:
      line_numbers: false

# =========================
# Plugins
# =========================
plugins:
  - jekyll-feed

# =========================
# Header navigation
# =========================
header_pages:
  - index.md
  - about.md
  - modules.md
  - team.md


